Disable irrelevant tests

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -37,18 +37,18 @@ jobs:
           skip: false
           all-python-versions: ${{(github.event_name != 'pull_request')}}
           coverage: true
-        - os: windows-latest
-          skip: false
-          all-python-versions: ${{(github.event_name != 'pull_request')}}
-          coverage: false
-        - os: macos-latest
-          skip: false
-          all-python-versions: ${{(github.event_name != 'pull_request')}}
-          coverage: false
-        - os: macos-15-intel
-          skip: ${{ github.event_name == 'pull_request' }}
-          all-python-versions: true
-          coverage: false
+        # - os: windows-latest
+        #   skip: false
+        #   all-python-versions: ${{(github.event_name != 'pull_request')}}
+        #   coverage: false
+        # - os: macos-latest
+        #   skip: false
+        #   all-python-versions: ${{(github.event_name != 'pull_request')}}
+        #   coverage: false
+        # - os: macos-15-intel
+        #   skip: ${{ github.event_name == 'pull_request' }}
+        #   all-python-versions: true
+        #   coverage: false
 
       fail-fast: false
 
@@ -60,35 +60,35 @@ jobs:
       coverage: ${{ matrix.config.coverage }}
     secrets: inherit
 
-  test-gcc14:
-    needs: lint
-    uses: ./.github/workflows/test_gcc14.yml
+  # test-gcc14:
+  #   needs: lint
+  #   uses: ./.github/workflows/test_gcc14.yml
 
-  test-docs:
-    needs: lint
-    runs-on: ubuntu-latest
-    if: success() || failure()
-    steps:
-      - uses: actions/checkout@v6
-      - uses: actions/setup-python@v6
-        with:
-          python-version: "3.11"
-      - name: Update pip and install dependencies
-        shell: bash -l {0}
-        run: |
-          python -m pip install --upgrade pip
-          python -m pip install --group ci --group docs --group test
-          python -m pip install .[matplotlib,phonopy-reader,brille]
-      - name: Run Sphinx doctests
-        working-directory: ./doc
-        shell: bash -l {0}
-        run: sphinx-build -c source -b doctest source .
-      - name: Upload docstest results
-        if: success() || failure()
-        uses: actions/upload-artifact@v4
-        with:
-          name: Doctest results
-          path: doc/output.txt
+  # test-docs:
+  #   needs: lint
+  #   runs-on: ubuntu-latest
+  #   if: success() || failure()
+  #   steps:
+  #     - uses: actions/checkout@v6
+  #     - uses: actions/setup-python@v6
+  #       with:
+  #         python-version: "3.11"
+  #     - name: Update pip and install dependencies
+  #       shell: bash -l {0}
+  #       run: |
+  #         python -m pip install --upgrade pip
+  #         python -m pip install --group ci --group docs --group test
+  #         python -m pip install .[matplotlib,phonopy-reader,brille]
+  #     - name: Run Sphinx doctests
+  #       working-directory: ./doc
+  #       shell: bash -l {0}
+  #       run: sphinx-build -c source -b doctest source .
+  #     - name: Upload docstest results
+  #       if: success() || failure()
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: Doctest results
+  #         path: doc/output.txt
 
   publish-test-results:
     needs: test
@@ -120,6 +120,7 @@ jobs:
         continue-on-error: true
         with:
           coverageFile: 'artifacts/coverage-combined.xml'
+          sourceDir: euphonic
           token: ${{ secrets.GITHUB_TOKEN }}
 
   publish-coverage-badge:
